"""
This type stub file was generated by pyright.
"""

import sys
import warnings
from os import path

"""
This type stub file was generated by pyright.
"""
__copyright__ = ...
__license__ = ...
if (sys.version_info.major, sys.version_info.minor) < (3, 3):
    ...
