"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__copyright__ = ...
__license__ = ...
SECTION = ...
FILE_TOO_LARGE_THRESHOLD = ...
def find_imports(importer_config, files_or_directories, logfile=...):
    """Given an importer configuration, search for files that can be imported in the
    list of files or directories, run the signature checks on them and return a list
    of (filename, importers), where 'importers' is a list of importers that matched
    the file.

    Args:
      importer_config: a list of importer instances that define the config.
      files_or_directories: a list of files of directories to walk recursively and
                            hunt for files to import.
      logfile: A file object to write log entries to, or None, in which case no log is
        written out.
    Yields:
      Triples of filename found, textified contents of the file, and list of
      importers matching this file.
    """
    ...

def identify(importers_list, files_or_directories):
    """Run the identification loop.

    Args:
      importers_list: A list of importer instances.
      files_or_directories: A list of strings, files or directories.
    """
    ...

DESCRIPTION = ...
def add_arguments(parser):
    """Add arguments for the identify command."""
    ...

def run(_, __, importers_list, files_or_directories, hooks=...):
    """Run the subcommand."""
    ...

