"""
This type stub file was generated by pyright.
"""

"""Tests for individual booking methods.

Note that these should be already covered by the tests in booking_full_test, but
we may want to add more tests here, just calling each method directly and
covering all the possible branches.
"""
__copyright__ = ...
__license__ = ...
if __name__ == '__main__':
    ...
