"""
This type stub file was generated by pyright.
"""

import unittest
from unittest import mock
from beancount.parser import cmptest, parser
from beancount.utils import test_utils

"""
Tests for grammar parser.
"""
__copyright__ = ...
__license__ = ...
def check_list(test, objlist, explist): # -> None:
    """Assert the list of objects against the expected specification.

    Args:
      test: the instance of the test object, used for generating assertions.
      objlist: the list of objects returned.

      explist: the list of objects expected. 'explist' can be an integer, to
               check the length of the list; if it is a list of types, the types
               are checked against the types of the objects in the list. This is
               meant to be a convenient method.
    """
    ...

def raise_exception(*args, **kwargs):
    """Raises a ValueError exception.

    Args:
      *args: Callback arguments.
      *kwargs: Callback keyword arguments.
    Raises:
      ValueError: Unconditionally.
    """
    ...

class TestParserEntryTypes(unittest.TestCase):
    """Basic smoke test one entry of each kind."""
    @parser.parse_doc()
    def test_entry_transaction_one_string(self, entries, _, __): # -> None:
        """
          2013-05-18 * "Nice dinner at Mermaid Inn"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_entry_transaction_two_strings(self, entries, _, __): # -> None:
        """
          2013-05-18 * "Mermaid Inn" "Nice dinner"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_entry_transaction_three_strings(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Mermaid Inn" "Nice dinner" "With Caroline"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_entry_transaction_with_txn_keyword(self, entries, _, __): # -> None:
        """
          2013-05-18 txn "Nice dinner at Mermaid Inn"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_entry_balance(self, entries, _, __): # -> None:
        """
          2013-05-18 balance Assets:US:BestBank:Checking  200 USD
          2013-05-18 balance Assets:US:BestBank:Checking  200 ~ 0.002 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_entry_balance_with_cost(self, entries, errors, __): # -> None:
        """
          2013-05-18 balance Assets:Investments  10 MSFT {45.30 USD}
        """
        ...
    
    @parser.parse_doc()
    def test_entry_open_1(self, entries, _, __): # -> None:
        """
          2013-05-18 open Assets:US:BestBank:Checking
        """
        ...
    
    @parser.parse_doc()
    def test_entry_open_2(self, entries, _, __): # -> None:
        """
          2013-05-18 open Assets:US:BestBank:Checking   USD
        """
        ...
    
    @parser.parse_doc()
    def test_entry_open_3(self, entries, errors, __): # -> None:
        """
          2013-05-18 open Assets:Cash   USD,CAD,EUR
        """
        ...
    
    @parser.parse_doc()
    def test_entry_open_4(self, entries, errors, __): # -> None:
        """
          2013-05-18 open Assets:US:Vanguard:VIIPX  VIIPX  "STRICT"
        """
        ...
    
    @parser.parse_doc()
    def test_entry_open_5(self, entries, errors, __): # -> None:
        """
          2013-05-18 open Assets:US:Vanguard:VIIPX    "STRICT"
        """
        ...
    
    @parser.parse_doc()
    def test_entry_close(self, entries, _, __): # -> None:
        """
          2013-05-18 close Assets:US:BestBank:Checking
        """
        ...
    
    @parser.parse_doc()
    def test_entry_commodity(self, entries, _, __): # -> None:
        """
          2013-05-18 commodity MSFT
        """
        ...
    
    @parser.parse_doc()
    def test_entry_pad(self, entries, _, __): # -> None:
        """
          2013-05-18 pad Assets:US:BestBank:Checking  Equity:Opening-Balances
        """
        ...
    
    @parser.parse_doc()
    def test_entry_event(self, entries, _, __): # -> None:
        """
          2013-05-18 event "location" "New York, USA"

          ;; Test empty event.
          2013-05-18 event "location" ""
        """
        ...
    
    @parser.parse_doc()
    def test_entry_query(self, entries, _, __): # -> None:
        """
          2013-05-18 query "cash" "SELECT SUM(position) WHERE currency = 'USD'"
        """
        ...
    
    @parser.parse_doc()
    def test_entry_note(self, entries, _, __): # -> None:
        """
          2013-05-18 note Assets:US:BestBank:Checking  "Blah, di blah."
        """
        ...
    
    @parser.parse_doc()
    def test_entry_document(self, entries, _, __): # -> None:
        """
          2013-05-18 document Assets:US:BestBank:Checking "/Accounting/statement.pdf"
        """
        ...
    
    @parser.parse_doc()
    def test_entry_price(self, entries, _, __): # -> None:
        """
          2013-05-18 price USD   1.0290 CAD
        """
        ...
    
    @parser.parse_doc()
    def test_entry_custom(self, entries, _, __): # -> None:
        """
          2013-05-18 custom "budget" "weekly < 1000.00 USD" 2016-02-28 TRUE 43.03 USD 23
        """
        ...
    


class TestWhitespace(unittest.TestCase):
    """Tests for handling of whitespace and indent."""
    @parser.parse_doc(expect_errors=True)
    def test_indent_error_0(self, entries, errors, _): # -> None:
        """
          2020-07-28 open Assets:Foo
            2020-07-28 open Assets:Bar
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_indent_error_1(self, entries, errors, _): # -> None:
        """
          2020-07-28 open Assets:Foo

            2020-07-28 open Assets:Bar
        """
        ...
    


class TestParserComplete(unittest.TestCase):
    """Tests of completion of balance."""
    @parser.parse_doc()
    def test_entry_transaction_single_posting_at_zero(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Nice dinner at Mermaid Inn"
            Expenses:Restaurant         0 USD
        """
        ...
    
    @parser.parse_doc()
    def test_entry_transaction_imbalance_from_single_posting(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Nice dinner at Mermaid Inn"
            Expenses:Restaurant         100 USD
        """
        ...
    


class TestUglyBugs(unittest.TestCase):
    """Test all kinds of stupid sh*t that will inevitably occur in practice."""
    @parser.parse_doc()
    def test_empty_1(self, entries, errors, _): # -> None:
        ""
        ...
    
    @parser.parse_doc()
    def test_empty_2(self, entries, errors, _): # -> None:
        """

        """
        ...
    
    @parser.parse_doc()
    def test_comment(self, entries, errors, _): # -> None:
        """
        ;; This is some comment.
        """
        ...
    
    @parser.parse_doc()
    def test_extra_whitespace_note(self, entries, errors, _): # -> None:
        """
        2013-07-11 note Assets:Cash "test"
          ;;
        """
        ...
    
    def test_extra_whitespace_transaction(self): # -> None:
        ...
    
    def test_extra_whitespace_comment(self): # -> None:
        ...
    
    @parser.parse_doc()
    def test_indent_eof(self, entries, errors, _): # -> None:
        "\t"
        ...
    
    @parser.parse_doc()
    def test_comment_eof(self, entries, errors, _): # -> None:
        "; comment"
        ...
    
    @parser.parse_doc()
    def test_no_empty_lines(self, entries, errors, _): # -> None:
        """
          2013-05-01 open Assets:Cash   USD,CAD,EUR
          2013-05-02 close Assets:US:BestBank:Checking
          2013-05-03 pad Assets:US:BestBank:Checking  Equity:Opening-Balances
          2013-05-04 event "location" "New York, USA"
          2013-05-05 * "Payee" "Narration"
            Assets:US:BestBank:Checking   100.00 USD
            Assets:Cash                  -100.00 USD
          2013-05-06 note Assets:US:BestBank:Checking  "Blah, di blah."
          2013-05-07 price USD   1.0290 CAD
        """
        ...
    


class TestComment(unittest.TestCase):
    @parser.parse_doc()
    def test_comment_before_transaction(self, entries, errors, _): # -> None:
        """
        ; Hi
        2015-06-07 *
          Assets:Cash   1 USD
          Assets:Cash   -1 USD
        """
        ...
    
    @parser.parse_doc()
    def test_comment_after_transaction(self, entries, errors, _): # -> None:
        """
        2015-06-07 *
          Assets:Cash   1 USD
          Assets:Cash   -1 USD
        ; Hi
        """
        ...
    
    @parser.parse_doc()
    def test_comment_between_postings(self, entries, errors, _): # -> None:
        """
        2015-06-07 *
          Assets:Cash   1 USD
          ; Hi
          Assets:Cash   -1 USD
        """
        ...
    
    @parser.parse_doc()
    def test_comment_after_posting(self, entries, errors, _): # -> None:
        """
        2015-06-07 *
          Assets:Cash   1 USD    ; Hi
          Assets:Cash   -1 USD
        """
        ...
    
    @parser.parse_doc()
    def test_comment_after_transaction_start(self, entries, errors, _): # -> None:
        """
        2015-06-07 *     ; Hi
          Assets:Cash   1 USD
          Assets:Cash   -1 USD
        """
        ...
    


class TestPushPopTag(unittest.TestCase):
    @parser.parse_doc(expect_errors=True)
    def test_tag_left_unclosed(self, entries, errors, _): # -> None:
        """
          pushtag #trip-to-nowhere
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_pop_invalid_tag(self, entries, errors, _): # -> None:
        """
          poptag #trip-to-nowhere
        """
        ...
    


class TestPushPopMeta(unittest.TestCase):
    @parser.parse_doc()
    def test_pushmeta_normal(self, entries, errors, _): # -> None:
        """
          pushmeta location: "Lausanne, Switzerland"

          2015-06-07 * "Something"
            Assets:Something   1 USD
            Assets:Something  -1 USD

          popmeta location:
        """
        ...
    
    @parser.parse_doc()
    def test_pushmeta_shadow(self, entries, errors, _): # -> None:
        """
          pushmeta location: "Lausanne, Switzerland"

          2015-06-07 * "Something"
            location: "Paris, France"
            Assets:Something   1 USD
            Assets:Something  -1 USD

          popmeta location:
        """
        ...
    
    @parser.parse_doc()
    def test_pushmeta_override(self, entries, errors, _): # -> None:
        """
          pushmeta location: "Lausanne, Switzerland"

          2015-06-01 * "Something"
            Assets:Something   1 USD
            Assets:Something  -1 USD

          pushmeta location: "Paris, France"

          2015-06-02 * "Something"
            Assets:Something   1 USD
            Assets:Something  -1 USD

          popmeta location:
          popmeta location:
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_pushmeta_invalid_pop(self, entries, errors, _): # -> None:
        """
          popmeta location:
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_pushmeta_forgotten(self, entries, errors, _): # -> None:
        """
          pushmeta location: "Lausanne, Switzerland"
        """
        ...
    


class TestMultipleLines(unittest.TestCase):
    @parser.parse_doc()
    def test_multiline_narration(self, entries, errors, _): # -> None:
        """
          2014-07-11 * "Hello one line
          and yet another,
          and why not another!"
            Expenses:Restaurant         100 USD
            Assets:Cash                -100 USD
        """
        ...
    


class TestSyntaxErrors(unittest.TestCase):
    """Test syntax errors that occur within the parser.
    One of our goals is to recover and report without ever
    bailing out with an exception."""
    @parser.parse_doc(expect_errors=True)
    def test_lexer_default_rule_1(self, entries, errors, _): # -> None:
        """
          Account:*:Bla
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_lexer_default_rule_2(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Nice dinner at Mermaid Inn"
            Expenses:Resta(urant        100 USD
            Expenses:Tips                10 USD
            Assets:US:Cash             -110 USD

          2013-05-20 balance Assets:US:Cash  -110 USD
        """
        ...
    
    @parser.parse_doc()
    def test_no_final_newline(self, entries, errors, _): # -> None:
        """
          2014-11-02 *
            Assets:Something   1 USD
            Assets:Other      -1 USD"""
        ...
    


class TestParserOptions(unittest.TestCase):
    @parser.parse_doc()
    def test_option_single_value(self, entries, errors, options_map): # -> None:
        """
          option "title" "Super Rich"

        """
        ...
    
    @parser.parse_doc()
    def test_option_list_value(self, entries, errors, options_map): # -> None:
        """
          option "documents" "/path/docs/a"
          option "documents" "/path/docs/b"
          option "documents" "/path/docs/c"

        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_invalid_option(self, entries, errors, options_map): # -> None:
        """
          option "bladibla_invalid" "Some value"

        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_readonly_option(self, entries, errors, options_map): # -> None:
        """
          option "filename" "gniagniagniagniagnia"

        """
        ...
    


class TestParserInclude(unittest.TestCase):
    def test_parse_nonexist(self): # -> None:
        ...
    
    @test_utils.docfile
    def test_include_absolute(self, filename): # -> None:
        """
          include "/some/absolute/filename.beancount"
        """
        ...
    
    @test_utils.docfile
    def test_include_relative(self, filename): # -> None:
        """
          include "some/relative/filename.beancount"
        """
        ...
    
    def test_include_relative_from_string(self): # -> None:
        ...
    


class TestParserPlugin(unittest.TestCase):
    @parser.parse_doc()
    def test_plugin(self, entries, errors, options_map): # -> None:
        """
          plugin "beancount.plugin.unrealized"
        """
        ...
    
    @parser.parse_doc()
    def test_plugin_with_config(self, entries, errors, options_map): # -> None:
        """
          plugin "beancount.plugin.unrealized" "Unrealized"
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_plugin_as_option(self, entries, errors, options_map): # -> None:
        """
          option "plugin" "beancount.plugin.unrealized"
        """
        ...
    


class TestDisplayContextOptions(unittest.TestCase):
    @parser.parse_doc()
    def test_render_commas_no(self, _, __, options_map): # -> None:
        """
          option "render_commas" "0"
        """
        ...
    
    @parser.parse_doc()
    def test_render_commas_yes(self, _, __, options_map): # -> None:
        """
          option "render_commas" "1"
        """
        ...
    
    @parser.parse_doc()
    def test_render_commas_yes2(self, _, __, options_map): # -> None:
        """
          option "render_commas" "TRUE"
        """
        ...
    


class TestMiscOptions(unittest.TestCase):
    @parser.parse_doc(expect_errors=False)
    def test_plugin_processing_mode__default(self, _, __, options_map): # -> None:
        """
        option "plugin_processing_mode" "default"
        """
        ...
    
    @parser.parse_doc(expect_errors=False)
    def test_plugin_processing_mode__raw(self, _, __, options_map): # -> None:
        """
        option "plugin_processing_mode" "raw"
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_plugin_processing_mode__invalid(self, _, errors, options_map): # -> None:
        """
        option "plugin_processing_mode" "invalid"
        """
        ...
    


class TestToleranceOptions(unittest.TestCase):
    @parser.parse_doc()
    def test_tolerance_defaults(self, _, __, options_map): # -> None:
        """
        """
        ...
    
    @parser.parse_doc()
    def test_inferred_tolerance_default(self, _, __, options_map): # -> None:
        """
          option "inferred_tolerance_default" "*:0"
          option "inferred_tolerance_default" "USD:0.05"
          option "inferred_tolerance_default" "JPY:0.5"
        """
        ...
    


class TestDeprecatedOptions(unittest.TestCase):
    @parser.parse_doc(expect_errors=True)
    def test_deprecated_plugin(self, _, errors, __): # -> None:
        """
          option "plugin" "beancount.plugins.module_name"
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_deprecated_option(self, _, errors, options_map): # -> None:
        """
          option "allow_pipe_separator" "TRUE"
        """
        ...
    


class TestParserLinks(unittest.TestCase):
    @parser.parse_doc()
    def test_links(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Something something" ^38784734873
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD

        """
        ...
    


class TestTransactions(unittest.TestCase):
    @parser.parse_doc()
    def test_simple_1(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Nice dinner at Mermaid Inn"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_simple_2(self, entries, errors, _): # -> None:
        """

          2013-05-18 * "Nice dinner at Mermaid Inn"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD

          2013-05-20 * "Duane Reade" "Toothbrush"
            Expenses:BathroomSupplies         4 USD
            Assets:US:BestBank:Checking      -4 USD

        """
        ...
    
    @parser.parse_doc()
    def test_empty_narration(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_no_narration(self, entries, errors, _): # -> None:
        """
          2013-05-18 *
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_payee_no_narration(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Mermaid Inn"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_too_many_strings(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "A" "B" "C"
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_link_and_then_tag(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Money from CC" ^610fa7f17e7a #trip
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_tag_then_link(self, entries, errors, _): # -> None:
        """
          2014-04-20 * #trip "Money from CC" ^610fa7f17e7a
            Expenses:Restaurant         100 USD
            Assets:US:Cash             -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_zero_prices(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Like a conversion entry"
            Equity:Conversions         100 USD @ 0 XFER
            Equity:Conversions         101 CAD @ 0 XFER
            Equity:Conversions         102 AUD @ 0 XFER
        """
        ...
    
    @parser.parse_doc(expect_errors=False)
    def test_zero_units(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Zero number of units"
            Assets:Investment         0 HOOL {500.00 USD}
            Assets:Cash               0 USD
        """
        ...
    
    @parser.parse_doc()
    def test_zero_costs(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Like a conversion entry"
            Assets:Investment         10 HOOL {0 USD}
            Assets:Cash                0 USD
        """
        ...
    
    @parser.parse_doc()
    def test_imbalance(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Busted!"
            Assets:Checking         100 USD
            Assets:Checking         -99 USD
        """
        ...
    
    @parser.parse_doc()
    def test_no_postings(self, entries, errors, _): # -> None:
        """
          2014-07-17 * "(JRN) INTRA-ACCOUNT TRANSFER" ^795422780
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_blank_line_not_allowed(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Busted!"
            Assets:Checking         100 USD

            Assets:Checking         -99 USD
        """
        ...
    
    def test_blank_line_with_spaces_not_allowed(self): # -> None:
        ...
    
    @parser.parse_doc()
    def test_tags_after_first_line(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Links and tags on subsequent lines" #basetag ^baselink
            #tag1 #tag2
            ^link1 #tag3
            #tag4 ^link2
            ^link3 ^link4
            #tag6
            ^link5
            Assets:Checking         100 USD
            Assets:Checking         -99 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_tags_after_first_posting(self, entries, errors, _): # -> None:
        """
          2014-04-20 * "Links and tags on subsequent lines" #basetag ^baselink
            Assets:Checking         100 USD
            #tag1 ^link1
            Assets:Checking         -99 USD
        """
        ...
    


class TestParseLots(unittest.TestCase):
    maxDiff = ...
    @parser.parse_doc()
    def test_cost_none(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL   45.23 USD
            Assets:Invest:Cash  -45.23 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_empty(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL   20 AAPL {}
            Assets:Invest:Cash  -20 AAPL
        """
        ...
    
    @parser.parse_doc()
    def test_cost_amount(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL      20 AAPL {45.23 USD}
            Assets:Invest:Cash  -90.46 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_date(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL   20 AAPL {2014-12-26}
            Assets:Invest:Cash  -20 AAPL
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_label(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL   20 AAPL {"d82d55a0dbe8"}
            Assets:Invest:Cash  -20 AAPL
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True, expect_errors=True)
    def test_cost_merge(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL   20 AAPL {*}
            Assets:Invest:Cash  -20 AAPL
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_two_components(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL    1 AAPL {45.23 USD, 2014-12-26}
            Assets:Invest:AAPL    1 AAPL {2014-12-26, 45.23 USD}
            Assets:Invest:AAPL    1 AAPL {45.23 USD, "d82d55a0dbe8"}
            Assets:Invest:AAPL    1 AAPL {"d82d55a0dbe8", 45.23 USD}
            Assets:Invest:AAPL    1 AAPL {2014-12-26, "d82d55a0dbe8"}
            Assets:Invest:AAPL    1 AAPL {"d82d55a0dbe8", 2014-12-26}
        """
        ...
    
    @parser.parse_doc()
    def test_cost_three_components(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL    1 AAPL {45.23 USD, 2014-12-26, "d82d55a0dbe8"}
            Assets:Invest:AAPL    1 AAPL {2014-12-26, 45.23 USD, "d82d55a0dbe8"}
            Assets:Invest:AAPL    1 AAPL {45.23 USD, "d82d55a0dbe8", 2014-12-26}
            Assets:Invest:AAPL    1 AAPL {2014-12-26, "d82d55a0dbe8", 45.23 USD}
            Assets:Invest:AAPL    1 AAPL {"d82d55a0dbe8", 45.23 USD, 2014-12-26}
            Assets:Invest:AAPL    1 AAPL {"d82d55a0dbe8", 2014-12-26, 45.23 USD}
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_cost_repeated(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL       1 AAPL {45.23 USD, 45.24 USD}
            Assets:Invest:Cash  -45.23 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_cost_repeated_date(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL    1 AAPL {45.23 USD, 2014-12-26, 2014-12-27}
            Assets:Invest:Cash   -1 AAPL
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_cost_repeated_label(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL       1 AAPL {"aaa", "bbb", 45.23 USD}
            Assets:Invest:Cash  -45.23 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True, allow_incomplete=True)
    def test_cost_repeated_merge(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL       1 AAPL {*, *}
            Assets:Invest:Cash  -45.23 USD
        """
        ...
    
    @parser.parse_doc()
    def test_cost_both_costs(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL       10 AAPL {45.23 # 9.95 USD}
            Assets:Invest:Cash  -110.36 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_total_cost_only(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL      10 AAPL {# 9.95 USD}
            Assets:Invest:Cash  -19.90 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_total_empty_total(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL      20 AAPL {45.23 # USD}
            Assets:Invest:Cash  -45.23 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_total_just_currency(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL   20 AAPL {USD}
            Assets:Invest:AAPL   20 AAPL { # USD}
            Assets:Invest:Cash    0 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_cost_with_slashes(self, entries, errors, _): # -> None:
        """
          2014-01-01 *
            Assets:Invest:AAPL      1.1 AAPL {45.23 USD / 2015-07-16 / "blabla"}
            Assets:Invest:Cash   -45.23 USD
        """
        ...
    


class TestCurrencies(unittest.TestCase):
    @parser.parse_doc()
    def test_parse_currencies(self, entries, errors, _): # -> None:
        """
          2014-01-19 open Assets:Underscore    DJ_EURO
          2014-01-19 open Assets:Period        DJ.EURO
          2014-01-19 open Assets:Apostrophe    DJ'EURO
          2014-01-19 open Assets:Numbers       EURO123
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_different_cost_and_price_currency(self, entries, errors, _): # -> None:
        """
          2018-03-21 * "Convert MR to KrisFlyer"
            Assets:Test                -100 MR {0.0075 USD} @ 1 KRISFLYER
            Assets:Krisflyer            100 KRISFLYER
        """
        ...
    


class TestTotalsAndSigns(unittest.TestCase):
    @parser.parse_doc(expect_errors=False)
    def test_zero_amount(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      0 MSFT {200.00 USD}
            Assets:Investments:Cash      0 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=False)
    def test_zero_cost(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      -10 MSFT {0.00 USD}
            Assets:Investments:Cash     0.00 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=False)
    def test_cost_negative(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      -10 MSFT {-200.00 USD}
            Assets:Investments:Cash  2000.00 USD
        """
        ...
    
    @parser.parse_doc()
    def test_total_cost(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT {{2,000 USD}}
            Assets:Investments:Cash  -20000 USD

          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT {{2000 USD, 2014-02-25}}
            Assets:Investments:Cash  -20000 USD

          2013-06-01 * ""
            Assets:Investments:MSFT      -10 MSFT {{2,000 USD}}
            Assets:Investments:Cash    20000 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_total_cost__invalid(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT {{100 # 2,000 USD}}
            Assets:Investments:Cash  -20000 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=False)
    def test_total_cost_negative(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      -10 MSFT {{-200.00 USD}}
            Assets:Investments:Cash   200.00 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_price_negative(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      -10 MSFT @ -200.00 USD
            Assets:Investments:Cash  2000.00 USD
        """
        ...
    
    @parser.parse_doc()
    def test_total_price_positive(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT        10 MSFT @@ 2000.00 USD
            Assets:Investments:Cash  -2000.00 USD
        """
        ...
    
    @parser.parse_doc()
    def test_total_price_negative(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT       -10 MSFT @@ 2000.00 USD
            Assets:Investments:Cash  20000.00 USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_total_price_inverted(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT         10 MSFT @@ -2000.00 USD
            Assets:Investments:Cash   20000.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True, expect_errors=True)
    def test_total_price_with_missing(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT            MSFT @@ 2000.00 USD
            Assets:Investments:Cash   20000.00 USD
        """
        ...
    


class TestBalance(unittest.TestCase):
    @parser.parse_doc()
    def test_total_price(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT @@ 2000 USD
            Assets:Investments:Cash  -20000 USD
        """
        ...
    
    @parser.parse_doc()
    def test_total_cost(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT {{2,000 USD}}
            Assets:Investments:Cash  -20000 USD

          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT {{2000 USD, 2014-02-25}}
            Assets:Investments:Cash  -20000 USD
        """
        ...
    


class TestMetaData(unittest.TestCase):
    @staticmethod
    def strip_meta(meta):
        """Removes the filename, lineno from the postings metadata."""
        ...
    
    @parser.parse_doc()
    def test_metadata_transaction__begin(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            test: "Something"
            Assets:Investments:MSFT      10 MSFT @@ 2000 USD
            Assets:Investments:Cash  -20000 USD
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_transaction__middle(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT @@ 2000 USD
            test: "Something"
            Assets:Investments:Cash  -20000 USD
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_transaction__end(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            Assets:Investments:MSFT      10 MSFT @@ 2000 USD
            Assets:Investments:Cash  -20000 USD
            test: "Something"
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_transaction__many(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            test1: "Something"
            Assets:Investments:MSFT      10 MSFT @@ 2000 USD
            test2: "has"
            test3: "to"
            Assets:Investments:Cash  -20000 USD
            test4: "come"
            test5: "from"
            test6: "this"
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_transaction__indented(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
              test1: "Something"
            Assets:Investments:MSFT      10 MSFT @@ 2000 USD
              test2: "has"
              test3: "to"
            Assets:Investments:Cash  -20000 USD
              test4: "come"
              test5: "from"
              test6: "this"
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_metadata_transaction__repeated(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            test: "Bananas"
            test: "Apples"
            test: "Oranges"
            Assets:Investments   100 USD
              test: "Bananas"
              test: "Apples"
            Income:Investments  -100 USD
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_empty(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "blabla"
            oranges:
            bananas:

          2013-05-19 open Assets:Something
            apples:
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_other(self, entries, errors, _): # -> None:
        """
          2013-01-01 open Equity:Other

          2013-01-01 open Assets:Investments
            test1: "Something"
            test2: "Something"

          2014-01-01 close Assets:Investments
            test1: "Something"

          2013-01-10 note Assets:Investments "Bla"
            test1: "Something"

          2013-01-31 pad Assets:Investments Equity:Other
            test1: "Something"

          2013-02-01 balance Assets:Investments  111.00 USD
            test1: "Something"

          2013-03-01 event "location" "Nowhere"
            test1: "Something"

          2013-03-01 document Assets:Investments "/path/to/something.pdf"
            test1: "Something"

          2013-03-01 price  HOOL  500 USD
            test1: "Something"
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_data_types(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            string: "Something"
            account: Assets:Investments:Cash
            date: 2012-01-01
            currency: HOOL
            tag: #trip-florida
            number: 345.67
            amount: 345.67 USD
            boolt: TRUE
            boolf: FALSE
        """
        ...
    
    @parser.parse_doc()
    def test_metadata_key_syntax(self, entries, errors, _): # -> None:
        """
          2013-05-18 * ""
            nameoncard: "Jim"
            nameOnCard: "Joe"
            name-on-card: "Bob"
            name_on_card: "John"
        """
        ...
    


class TestArithmetic(unittest.TestCase):
    maxDiff = ...
    @parser.parse_doc()
    def test_number_expr__add(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something    12 + 3 USD
            Assets:Something   7.5 + 3.1 USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__subtract(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something    12 - 3 USD
            Assets:Something   7.5 - 3.1 USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__multiply(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something    12 * 3 USD
            Assets:Something   7.5 * 3.1 USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__divide(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something    12 / 3 USD
            Assets:Something   7.5 / 3 USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__negative(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something    -12 USD
            Assets:Something   -7.5 USD
            Assets:Something   - 7.5 USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__positive(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something    +12 USD
            Assets:Something   -7.5 USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__precedence(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something   2 * 3 + 4 USD
            Assets:Something   2 + 3 * 4 USD
            Assets:Something   2 + -3 * 4 USD
            Assets:Something   (2 + -3) * 4 USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__groups(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something   (2 + -3) * 4 USD
            Assets:Something   2 * (2 + -3) USD
        """
        ...
    
    @parser.parse_doc()
    def test_number_expr__different_places(self, entries, errors, _): # -> None:
        """
          2013-05-18 * "Test"
            Assets:Something   -(3 * 4) HOOL {120.01 * 2.1 USD} @ 134.02 * 2.1 USD
            Assets:Something   1000000 USD ;; No balance checks.
          2014-01-01 balance Assets:Something  3 * 4 * 120.01 * 2.1  USD
            number: -(5662.23 + 22.3)
        """
        ...
    


class TestLexerAndParserErrors(cmptest.TestCase):
    """There are a number of different paths where errors may occur. This test case
    intends to exercise them all. This docstring explains how it all works (it's
    a bit complicated).

    Expectations: The parser.parse_*() functions never raise exceptions, they
    always produce a list of error messages on the builder objects. This is by
    design: we have a single way to produce and report errors.

    The lexer may fail in two different ways:

    * Invalid Token: yylex() is invoked by the parser... the lexer rules are
      processed and all fail and the default rule of the lexer gets called at
      {bf253a29a820}. The lexer immediately switches to its INVALID subparser to
      chomp the rest of the invalid token's unrecognized characters until it
      hits some whitespace (see {bba169a1d35a}). A new LexerError is created and
      accumulated by calling the build_lexer_error() method on the builder
      object using this text (see {0e31aeca3363}). The lexer then returns a
      LEX_ERROR token to the parser, which fails as below.

    * Lexer Builder Exception: The lexer recognizes a valid token and invokes a
      callback on the builder using BUILD_LEX(). However, an exception is raised
      in that Python code ({3cfb2739349a}). The exception's error text is saved
      and this is used to build an error on the lexer builder at
      build_lexer_error().

    For both the errors above, when the parser receives the LEX_ERROR token, it
    is an unexpected token (because none of the rules handle it), so it calls
    yyerror() {ca6aab8b9748}. Because the lexer has already registered an error
    in the error list, in yyerror() we simply ignore it and do nothing (see
    {ca6aab8b9748}).

    Error recovery then proceeds by successive reductions of the "error" grammar
    rules which discards all tokens until a valid rule can be reduced again
    ({3d95e55b654e}). Note that Bison issues a single call to yyerror() and
    keeps reducing invalid "error" rules silently until another one succeeds. We
    ignore the directive and restart parsing from that point on. If the error
    occurred on a posting in progress of being parsed, because the "error" rule
    is not a valid posting of a transaction, that transaction will not be
    produced and thus is ignore, which is what we want.

    The parser may itself also encounter two similar types of errors:

    * Syntax Error: There is an error in the grammar of the input. yyparse() is
      called automatically by the generated code and we call
      build_grammar_error() to register the error. Error recovery proceeds
      similarly to what was described previously.

    * Grammar Builder Exception: A grammar rule is reduced successfully, a
      builder method is invoked and raises a Python exception. A macro in the
      code that invokes this method is used to catch this error and calls
      build_grammar_error_from_exception() to register an error and makes the
      parser issue an error with YYERROR (see {05bb0fb60e86}).

    We never call YYABORT anywhere so the yyparse() function should never return
    anything else than 0. If it does, we translate that into a Python
    RuntimeError exception, or a MemoryError exception (if yyparse() ran out of
    memory), see {459018e2905c}.
    """
    @parser.parse_doc(expect_errors=True)
    def test_lexer_invalid_token(self, entries, errors, _): # -> None:
        """
          2000-01-01 open ) USD
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_lexer_invalid_token__recovery(self, entries, errors, _): # -> None:
        """
          2000-01-01 open ) USD
          2000-01-02 open Assets:Something
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_lexer_exception(self, entries, errors, _): # -> None:
        """
          2000-13-32 open Assets:Something
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_lexer_exception__recovery(self, entries, errors, _): # -> None:
        """
          2000-13-32 open Assets:Something
          2000-01-02 open Assets:Working
        """
        ...
    
    def test_lexer_errors_in_postings(self): # -> None:
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_grammar_syntax_error(self, entries, errors, _): # -> None:
        """
          2000-01-01 open open
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_grammar_syntax_error__recovery(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          2000-01-02 open open
          2000-01-03 open Assets:After
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_grammar_syntax_error__recovery2(self, entries, errors, _): # -> None:
        """
          2000-01-01 open open
          2000-01-02 open Assets:Something
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_grammar_syntax_error__multiple(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          2000-01-02 open open
          2000-01-03 open Assets:After
          2000-01-04 close close
          2000-01-05 close Assets:After
        """
        ...
    
    def check_entries_errors(self, entries, errors): # -> None:
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.pushtag', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__pushtag(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          pushtag #sometag
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.poptag', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__poptag(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          poptag #sometag
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.option', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__option(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          option "operating_currency" "CAD"
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.include', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__include(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          include "answer.beancount"
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.plugin', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__plugin(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          plugin "answer.beancount"
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.amount', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__amount(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          2001-02-02 balance Assets:Before    23.00 USD
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.compound_amount', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__compound_amount(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          2001-02-02 *
            Assets:Before   10.00 HOOL {100.00 # 9.95 USD}
            Assets:After   -100.00 USD
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.cost_spec', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__lot_cost_date(self, entries, errors, _): # -> None:
        """
          2000-01-01 open Assets:Before
          2001-02-02 *
            Assets:Before   10.00 HOOL {100.00 USD}
            Assets:After   -100.00 USD
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.open', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__open(self, entries, errors, _): # -> None:
        """
          2010-01-01 balance Assets:Before  1 USD
          2000-01-01 open Assets:Before
          2010-01-01 close Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.close', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__close(self, entries, errors, _): # -> None:
        """
          2010-01-01 balance Assets:Before  1 USD
          2010-01-01 close Assets:Before
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.commodity', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__commodity(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 commodity USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.pad', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__pad(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 pad Assets:Before Assets:After
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.balance', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__balance(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 balance Assets:Before 100 USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.event', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__event(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 event "location" "New York, NY"
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.price', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__price(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 price HOOL 20 USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.note', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__note(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 note Assets:Before "Something something"
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.document', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__document(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 document Assets:Before "/path/to/document.png"
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.key_value', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__key_value(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 commodity HOOL
            key: "Value"
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.posting', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__posting(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 *
            Assets:Before   100.00 USD
            Assets:After   -100.00 USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.tag_link_new', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__tag_link_new(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 * "Payee" "Narration"
            Assets:Before   100.00 USD
            Assets:After   -100.00 USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.tag_link_TAG', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__tag_link_TAG(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 * "Payee" "Narration" #sometag
            Assets:Before   100.00 USD
            Assets:After   -100.00 USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.tag_link_LINK', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__tag_link_LINK(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 * "Payee" "Narration" ^somelink
            Assets:Before   100.00 USD
            Assets:After   -100.00 USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @parser.parse_doc()
    def test_grammar_exceptions__tag_link_PIPE(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 * "Payee" "Narration"
            Assets:Before   100.00 USD
            Assets:After   -100.00 USD
          2000-01-01 open Assets:Before
        """
        ...
    
    @mock.patch('beancount.parser.grammar.Builder.transaction', raise_exception)
    @parser.parse_doc(expect_errors=True)
    def test_grammar_exceptions__transaction(self, entries, errors, _): # -> None:
        """
          2010-01-01 close Assets:Before
          2010-01-01 * "Payee" "Narration"
            Assets:Before   100.00 USD
            Assets:After   -100.00 USD
          2000-01-01 open Assets:Before
        """
        ...
    


class TestIncompleteInputs(cmptest.TestCase):
    @parser.parse_doc(allow_incomplete=True)
    def test_units_full(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD
            Assets:Account2    -100.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD
            Assets:Account2
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_number(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD
            Assets:Account2            USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_currency(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD
            Assets:Account2    -100.00
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_with_cost(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     {300.00 USD}
            Assets:Account2    -600.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_number_with_cost(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1            HOOL {300.00 USD}
            Assets:Account2    -600.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_currency_with_cost(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1      10        {300.00 USD}
            Assets:Account2    -600.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_with_price(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account2                @ 1.2 USD
            Assets:Account1     100.00 USD @
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_number_with_price(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account2            CAD @ 1.2 USD
            Assets:Account1     100.00 USD @
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_units_missing_currency_with_price(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account2     120.00     @ 1.2 USD
            Assets:Account1     100.00 USD @
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_price_none(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_price_missing(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD @
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_price_missing_number(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD @ CAD
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_price_missing_currency(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     100.00 USD @ 1.2
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_full(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {150 # 5 USD}
            Assets:Account2     120.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_missing_number_per(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {# 5 USD}
            Assets:Account2     120.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_missing_number_total(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {150 # USD}
            Assets:Account2     120.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_no_number_total(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {150 USD}
            Assets:Account2     120.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_missing_numbers(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {USD}
            Assets:Account2     120.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_missing_currency(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {150}
            Assets:Account2     120.00 USD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_empty(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {}
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_empty_with_other(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {2015-09-21, "blablabla"}
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True)
    def test_cost_missing_basis(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {2015-09-21, "blablabla"}
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True, expect_errors=True)
    def test_cost_average(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {*}
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True, expect_errors=True)
    def test_cost_average_missing_basis(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {*, 2015-09-21, "blablabla"}
            Assets:Account2     120.00 CAD
        """
        ...
    
    @parser.parse_doc(allow_incomplete=True, expect_errors=True)
    def test_cost_average_with_other(self, entries, _, options_map): # -> None:
        """
          2010-05-28 *
            Assets:Account1     2 HOOL {*, 100.00 CAD, 2015-09-21, "blablabla"}
            Assets:Account2     120.00 CAD
        """
        ...
    


class TestMisc(cmptest.TestCase):
    @parser.parse_doc(expect_errors=False)
    def test_comment_in_postings(self, entries, errors, options_map): # -> None:
        """
          2017-06-27 * "Bitcoin network fee"
            ; Account: Pocket money
            Expenses:Crypto:NetworkFees           0.00082487 BTC
            Assets:Crypto:Bitcoin                -0.00082487 BTC
        """
        ...
    
    @parser.parse_doc(expect_errors=True)
    def test_comment_in_postings_invalid(self, entries, errors, options_map): # -> None:
        """
          2017-06-27 * "Bitcoin network fee"
            Expenses:Crypto:NetworkFees           0.00082487 BTC
          ; Account: Pocket money
            Assets:Crypto:Bitcoin                -0.00082487 BTC
        """
        ...
    


class TestDocument(unittest.TestCase):
    @parser.parse_doc()
    def test_document_no_tags_links(self, entries, _, __): # -> None:
        """
          2013-05-18 document Assets:US:BestBank:Checking "/Accounting/statement.pdf"
        """
        ...
    
    @parser.parse_doc()
    def test_document_tags(self, entries, _, __): # -> None:
        """
          pushtag #something
          2013-05-18 document Assets:US:BestBank:Checking "/Accounting/statement.pdf" #else
          poptag #something
        """
        ...
    
    @parser.parse_doc()
    def test_document_links(self, entries, _, __): # -> None:
        """
          2013-05-18 document Assets:US:BestBank:Checking "/statement.pdf" ^something
        """
        ...
    


class TestMethodsSignature(unittest.TestCase):
    def test_signatures(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
