"""
This type stub file was generated by pyright.
"""

"""
Declaration of options and their default values.
"""
__copyright__ = ...
__license__ = ...
def options_validate_processing_mode(value): # -> Literal['raw', 'default']:
    """Validate the options processing mode.

    Args:
      value: A string, the value provided as option.
    Returns:
      The new value, converted, if the conversion is successful.
    Raises:
      ValueError: If the value is invalid.
    """
    ...

def options_validate_plugin(value): # -> tuple[str | Any, str | Any | None]:
    """Validate the plugin option.

    Args:
      value: A string, the value provided as option.
    Returns:
      The new value, converted, if the conversion is successful.
    Raises:
      ValueError: If the value is invalid.
    """
    ...

def options_validate_tolerance(value): # -> Decimal | None:
    """Validate the tolerance option.

    Args:
      value: A string, the value provided as option.
    Returns:
      The new value, converted, if the conversion is successful.
    Raises:
      ValueError: If the value is invalid.
    """
    ...

def options_validate_tolerance_map(value): # -> tuple[str | Any, Decimal | None]:
    """Validate an option with a map of currency/tolerance pairs in a string.

    Args:
      value: A string, the value provided as option.
    Returns:
      The new value, converted, if the conversion is successful.
    Raises:
      ValueError: If the value is invalid.
    """
    ...

def options_validate_boolean(value): # -> bool:
    """Validate a boolean option.

    Args:
      value: A string, the value provided as option.
    Returns:
      The new value, converted, if the conversion is successful.
    Raises:
      ValueError: If the value is invalid.
    """
    ...

def options_validate_booking_method(value): # -> Booking:
    """Validate a booking method name.

    Args:
      value: A string, the value provided as option.
    Returns:
      The new value, converted, if the conversion is successful.
    Raises:
      ValueError: If the value is invalid.
    """
    ...

OptGroup = ...
OptDesc = ...
UNSET = ...
def Opt(name, default_value, example_value=..., converter=..., deprecated=..., alias=...): # -> OptDesc:
    """Alternative constructor for OptDesc, with default values.

    Args:
      name: See OptDesc.
      default_value: See OptDesc.
      example_value: See OptDesc.
      converter: See OptDesc.
      deprecated: See OptDesc.
      alias: See OptDesc.
    Returns:
      An instance of OptDesc.
    """
    ...

_TYPES = ...
OUTPUT_OPTION_GROUPS = ...
PUBLIC_OPTION_GROUPS = ...
OPTION_GROUPS = ...
OPTIONS = ...
OPTIONS_DEFAULTS = ...
READ_ONLY_OPTIONS = ...
def get_account_types(options): # -> AccountTypes:
    """Extract the account type names from the parser's options.

    Args:
      options: a dict of ledger options.
    Returns:
      An instance of AccountTypes, that contains all the prefixes.
    """
    ...

def get_previous_accounts(options): # -> tuple[str, str, str]:
    """Return account names for the previous earnings, balances and conversion accounts.

    Args:
      options: a dict of ledger options.
    Returns:
      A tuple of 3 account objects, for booking previous earnings,
      previous balances, and previous conversions.
    """
    ...

def get_current_accounts(options): # -> tuple[str, str]:
    """Return account names for the current earnings and conversion accounts.

    Args:
      options: a dict of ledger options.
    Returns:
      A tuple of 2 account objects, one for booking current earnings, and one
      for current conversions.
    """
    ...

def list_options(): # -> str:
    """Produce a formatted text of the available options and their description.

    Returns:
      A string, formatted nicely to be printed in 80 columns.
    """
    ...

