"""
This type stub file was generated by pyright.
"""

import unittest

__copyright__ = ...
__license__ = ...
class TestVersion(unittest.TestCase):
    def test_version_exists(self): # -> None:
        ...
    
    def test_compute_version_string(self): # -> None:
        ...
    
    def test_version(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
