"""
This type stub file was generated by pyright.
"""

"""Implement common options across all programs."""
__copyright__ = ...
__license__ = ...
def ArgumentParser(*args, **kwargs): # -> ArgumentParser:
    """Add a standard --version option to an ArgumentParser.

    Args:
      *args: Arguments for the parser.
      *kwargs: Keyword arguments for the parser.
    Returns:
      An instance of ArgumentParser, with our default options set.
    """
    ...

def compute_version_string(version, changeset, timestamp): # -> str:
    """Compute a version string from the changeset and timestamp baked in the parser.

    Args:
      version: A string, the version number.
      changeset: A string, a version control string identifying the commit of the version.
      timestamp: An integer, the UNIX epoch timestamp of the changeset.
    Returns:
      A human-readable string for the version.
    """
    ...

