"""
This type stub file was generated by pyright.
"""

import unittest

class APITests:
    def test_description(self): # -> None:
        ...
    
    def test_cursor_not_initialized(self): # -> None:
        ...
    
    def test_cursor_fetchone(self): # -> None:
        ...
    
    def test_cursor_fetchall(self): # -> None:
        ...
    
    def test_cursor_fethmany(self): # -> None:
        ...
    
    def test_cursor_iterator(self): # -> None:
        ...
    


class TestSQLite(APITests, unittest.TestCase):
    @classmethod
    def setUpClass(cls): # -> None:
        ...
    


class TestBeanquery(APITests, unittest.TestCase):
    @classmethod
    def setUpClass(cls): # -> None:
        ...
    


