"""
This type stub file was generated by pyright.
"""

import unittest

__copyright__ = ...
__license__ = ...
class TestNumerifySimple(unittest.TestCase):
    input_amounts = ...
    expected_types = ...
    expected_rows = ...
    def test_amount(self): # -> None:
        ...
    
    def test_position(self): # -> None:
        ...
    
    def test_inventory(self): # -> None:
        ...
    


class TestNumerifyIdentity(unittest.TestCase):
    def test_identity(self): # -> None:
        ...
    


class TestNumerifyInventory(unittest.TestCase):
    def test_inventory(self): # -> None:
        ...
    


class TestNumerifyPrecision(unittest.TestCase):
    def test_precision(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
