"""
This type stub file was generated by pyright.
"""

"""A library to run queries. This glues together all the parts of the query engine.
"""
__copyright__ = ...
__license__ = ...
def run_query(entries, options, query, *args, numberify=...): # -> tuple[tuple[Column, ...] | None, list[Any] | list[tuple[Any, ...]]]:
    """Compile and execute a query, return the result types and rows.

    Args:
      entries: A list of entries, as produced by the loader.
      options: A dict of options, as produced by the loader.
      query: A string, a single BQL query, optionally containing some new-style
        (e.g., {}) formatting specifications.
      args: A tuple of arguments to be formatted in the query. This is
        just provided as a convenience.
      numberify: If true, numberify the results before returning them.
    Returns:
      A pair of result types and result rows.
    Raises:
      ParseError: If the statement cannot be parsed.
      CompilationError: If the statement cannot be compiled.
    """
    ...

