"""
This type stub file was generated by pyright.
"""

import unittest
from beancount import loader

__copyright__ = ...
__license__ = ...
class TestSimple(unittest.TestCase):
    @loader.load_doc()
    def test_run_query(self, entries, _, options): # -> None:
        """
        2022-01-01 open Assets:Checking         USD
        2022-01-01 open Income:ACME             USD
        2022-01-01 open Expenses:Taxes:Federal  USD
        2022-01-01 open Assets:Federal:401k     IRAUSD
        2022-01-01 open Expenses:Taxes:401k     IRAUSD
        2022-01-01 open Assets:Vacation         VACHR
        2022-01-01 open Income:Vacation         VACHR
        2022-01-01 open Expenses:Vacation       VACHR
        2022-01-01 open Expenses:Tests          USD

        2022-01-01 * "ACME" "Salary"
          Assets:Checking           10.00 USD
          Income:ACME              -11.00 USD
          Expenses:Taxes:Federal     1.00 USD
          Assets:Federal:401k       -2.00 IRAUSD
          Expenses:Taxes:401k        2.00 IRAUSD
          Assets:Vacation               5 VACHR
          Income:Vacation              -5 VACHR

        2022-01-02 * "Holidays"
          Assets:Vacation              -1 VACHR
          Expenses:Vacation

        2022-01-03 * "Test"
          Assets:Checking            3.00 USD
          Expenses:Tests

        """
        ...
    


if __name__ == '__main__':
    ...
