"""
This type stub file was generated by pyright.
"""

class Table:
    columns = ...
    name = ...
    def __getitem__(self, name):
        ...
    
    @property
    def wildcard_columns(self): # -> dict_keys[Any, Any]:
        ...
    


class NullTable(Table):
    def __iter__(self): # -> Iterator[None]:
        ...
    


