"""
This type stub file was generated by pyright.
"""

"""Support for encrypted tests.
"""
__copyright__ = ...
__license__ = ...
def is_gpg_installed(): # -> Any | Match[str] | Literal[False] | None:
    """Return true if GPG 1.4.x or 2.x are installed, which is what we use and support."""
    ...

def is_encrypted_file(filename): # -> bool:
    """Return true if the given filename contains an encrypted file.

    Args:
      filename: A path string.
    Returns:
      A boolean, true if the file contains an encrypted file.
    """
    ...

def read_encrypted_file(filename): # -> str:
    """Decrypt and read an encrypted file without temporary storage.

    Args:
      filename: A string, the path to the encrypted file.
    Returns:
      A string, the contents of the file.
    Raises:
      OSError: If we could not properly decrypt the file.
    """
    ...

