"""
This type stub file was generated by pyright.
"""

import magic

"""Code that can guess a MIME type for a filename.

This attempts to identify the mime-type of a file suing

1. The built-in mimetypes library, then
2. python-magic (if available), and finally
3. some custom mappers for datatypes used in financial downloads, such as
   Quicken files.

"""
__copyright__ = ...
__license__ = ...
if not hasattr(magic, 'from_file'):
    magic = ...
EXTRA_FILE_TYPES = ...
def guess_file_type(filename): # -> str:
    """Attempt to guess the type of the input file.

    Args:
      filename: A string, the name of the file to guess the type for.
    Returns:
      A suitable mimetype string, or None if we could not guess.
    """
    ...

