"""
This type stub file was generated by pyright.
"""

import unittest
from beancount.utils import test_utils

__copyright__ = ...
__license__ = ...
class TestAccount(unittest.TestCase):
    def test_is_valid(self): # -> None:
        ...
    
    def test_account_join(self): # -> None:
        ...
    
    def test_account_split(self): # -> None:
        ...
    
    def test_parent(self): # -> None:
        ...
    
    def test_leaf(self): # -> None:
        ...
    
    def test_sans_root(self): # -> None:
        ...
    
    def test_root(self): # -> None:
        ...
    
    def test_has_component(self): # -> None:
        ...
    
    def test_commonprefix(self): # -> None:
        ...
    
    def test_parent_matcher(self): # -> None:
        ...
    
    def test_parents(self): # -> None:
        ...
    


class TestWalk(test_utils.TmpFilesTestBase):
    TEST_DOCUMENTS = ...
    def test_walk(self): # -> None:
        ...
    


class TestAccountTransformer(unittest.TestCase):
    def test_render(self): # -> None:
        ...
    
    def test_parse(self): # -> None:
        ...
    
    def test_noop(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
