"""
This type stub file was generated by pyright.
"""

import unittest

__copyright__ = ...
__license__ = ...
class TestAmount(unittest.TestCase):
    def test_constructor(self): # -> None:
        class Dummy:
            ...
        
        
    
    def test_mutation(self): # -> None:
        ...
    
    def test_fromstring(self): # -> None:
        ...
    
    def test_tostring(self): # -> None:
        ...
    
    def test_comparisons(self): # -> None:
        ...
    
    def test_hash(self): # -> None:
        ...
    
    def test_sort__explicit(self): # -> None:
        ...
    
    def test_sort__natural(self): # -> None:
        ...
    
    def test_neg(self): # -> None:
        ...
    
    def test_mult(self): # -> None:
        ...
    
    def test_div(self): # -> None:
        ...
    
    def test_add(self): # -> None:
        ...
    
    def test_sub(self): # -> None:
        ...
    
    def test_abs(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
