"""
This type stub file was generated by pyright.
"""

import unittest

__copyright__ = ...
__license__ = ...
class TestFlags(unittest.TestCase):
    ALLOW_NOT_UNIQUE = ...
    def test_unique_flags(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
