"""
This type stub file was generated by pyright.
"""

import unittest
from beancount import loader

__copyright__ = ...
__license__ = ...
TEST_INPUT = ...
class TestGetters(unittest.TestCase):
    def test_methods_coverage(self): # -> None:
        ...
    
    def test_get_accounts_use_map(self): # -> None:
        ...
    
    def test_get_accounts(self): # -> None:
        ...
    
    def test_get_entry_accounts(self): # -> None:
        ...
    
    def test_get_all_tags(self): # -> None:
        ...
    
    def test_get_all_payees(self): # -> None:
        ...
    
    def test_get_all_links(self): # -> None:
        ...
    
    def test_get_leveln_parent_accounts(self): # -> None:
        ...
    
    def test_get_dict_accounts(self): # -> None:
        ...
    
    def test_get_min_max_dates(self): # -> None:
        ...
    
    def test_get_active_years(self): # -> None:
        ...
    
    def test_get_account_open_close(self): # -> None:
        ...
    
    @loader.load_doc(expect_errors=True)
    def test_get_account_open_close__duplicates(self, entries, _, __): # -> None:
        """
        2014-01-01 open  Assets:Checking
        2014-01-02 open  Assets:Checking

        2014-01-28 close Assets:Checking
        2014-01-29 close Assets:Checking
        """
        ...
    
    def test_get_account_components(self): # -> None:
        ...
    
    def test_get_commodity_directives(self): # -> None:
        ...
    
    def test_get_values_meta__single(self): # -> None:
        ...
    
    def test_get_values_meta__multi(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
