"""
This type stub file was generated by pyright.
"""

import unittest

__copyright__ = ...
__license__ = ...
class TestDecimalPrecision(unittest.TestCase):
    def test_formatting(self): # -> None:
        ...
    


class TestToDecimal(unittest.TestCase):
    def test_ZERO(self): # -> None:
        ...
    
    def test_D(self): # -> None:
        ...
    
    def test_round_to(self): # -> None:
        ...
    
    def test_same_sign(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
